package com.projecteternal.content

import com.projecteternal.model.CombatStats
import com.projecteternal.model.EquipSlot
import com.projecteternal.model.ItemId
import com.projecteternal.model.ItemKind

/** Static item/resource catalog. */
object Items {
    private val all: Map<ItemId, ItemDefinition> = listOf(
        // ---- raw resources ----
        ItemDefinition("ore_iron", "Iron Ore", ItemKind.RESOURCE, tier = 1,
            buyPrice = 6, sellPrice = 3, icon = "🪨",
            description = "Raw iron ore. Feed it through a grinding wheel."),
        ItemDefinition("wood", "Hardwood Log", ItemKind.RESOURCE, tier = 1,
            buyPrice = 5, sellPrice = 2, icon = "🪵",
            description = "A sturdy log from the old woods."),
        ItemDefinition("herb_brightleaf", "Brightleaf", ItemKind.RESOURCE, tier = 1,
            buyPrice = 8, sellPrice = 4, icon = "🌿",
            description = "A faintly glowing leaf; base of many brews."),
        ItemDefinition("ore_coal", "Coal", ItemKind.RESOURCE, tier = 2,
            buyPrice = 20, sellPrice = 10, icon = "⚫",
            description = "Dense black coal, only found in deep seams."),
        ItemDefinition("meat_wolf", "Wolf Meat", ItemKind.RESOURCE, tier = 1,
            buyPrice = 9, sellPrice = 4, icon = "🍖",
            description = "Tough but edible."),
        ItemDefinition("pelt_wolf", "Wolf Pelt", ItemKind.RESOURCE, tier = 1,
            buyPrice = 7, sellPrice = 3, icon = "🧶",
            description = "Coarse grey fur."),
        ItemDefinition("meat_boar", "Boar Meat", ItemKind.RESOURCE, tier = 1,
            buyPrice = 11, sellPrice = 5, icon = "🥩"),
        ItemDefinition("pelt_boar", "Boar Hide", ItemKind.RESOURCE, tier = 1,
            buyPrice = 9, sellPrice = 4, icon = "🟤"),
        ItemDefinition("grain", "Grain", ItemKind.RESOURCE, tier = 1,
            buyPrice = 5, sellPrice = 2, icon = "🌾",
            description = "Golden grain from the terraces. Mill it for flour."),
        ItemDefinition("fish_carp", "River Carp", ItemKind.RESOURCE, tier = 1,
            buyPrice = 10, sellPrice = 4, icon = "🐟",
            description = "A quiet river catch. Perfect for drying."),

        // ---- processed materials ----
        ItemDefinition("iron_fragment", "Iron Fragment", ItemKind.MATERIAL, tier = 1,
            buyPrice = 12, sellPrice = 6, icon = "⚙️",
            description = "Ground ore ready for the smelter."),
        ItemDefinition("iron_ingot", "Iron Ingot", ItemKind.MATERIAL, tier = 1,
            buyPrice = 26, sellPrice = 13, icon = "🟦",
            description = "A cast iron ingot. Weapon-ready."),
        ItemDefinition("refined_iron", "Refined Iron", ItemKind.MATERIAL, tier = 2,
            buyPrice = 58, sellPrice = 29, icon = "🔷",
            description = "High-purity iron. Upgrades are forged from this."),
        ItemDefinition("steel", "Steel", ItemKind.MATERIAL, tier = 2,
            buyPrice = 130, sellPrice = 65, icon = "⚪"),
        ItemDefinition("lumber", "Lumber", ItemKind.MATERIAL, tier = 1,
            buyPrice = 14, sellPrice = 7, icon = "🟫"),
        ItemDefinition("flour", "Flour", ItemKind.MATERIAL, tier = 1,
            buyPrice = 12, sellPrice = 6, icon = "🫓",
            description = "Finely milled grain, ready for the oven."),
        ItemDefinition("rope", "Hemp Rope", ItemKind.MATERIAL, tier = 1,
            buyPrice = 10, sellPrice = 5, icon = "🪢",
            description = "Twisted cord. Fishing rods and fine craft trade on it."),
        ItemDefinition("machinery_part", "Machinery Part", ItemKind.MATERIAL, tier = 2,
            buyPrice = 240, sellPrice = 120, icon = "⚙️",
            description = "Precision fittings only an engineer could love."),
        ItemDefinition("core_storm", "Stormheart Core", ItemKind.MATERIAL, tier = 3,
            buyPrice = 700, sellPrice = 350, icon = "🌩️",
            description = "The still-warm heart of a storm herald."),
        ItemDefinition("roasted_meat", "Roasted Meat", ItemKind.CONSUMABLE, tier = 1,
            buyPrice = 20, sellPrice = 8, icon = "🍗", healAmount = 20,
            description = "Restores 20 health. Cooked at a campfire."),

        // ---- special resources ----
        ItemDefinition("shard_resonance", "Resonance Shard", ItemKind.MATERIAL, tier = 1,
            buyPrice = 40, sellPrice = 20, icon = "🔮",
            description = "Amplifies equipment. The heart of enhancement."),
        ItemDefinition("crystal_advanced", "Voidforged Crystal", ItemKind.MATERIAL, tier = 3,
            buyPrice = 400, sellPrice = 200, icon = "💠",
            description = "Required for ADVANCED enhancement tiers. Emberreach reagent."),
        ItemDefinition("crystal_guardian", "Guardian Core", ItemKind.MATERIAL, tier = 2,
            buyPrice = 250, sellPrice = 120, icon = "🟣",
            description = "Held by the ruin guardian. Proof of a great hunt."),

        ItemDefinition("catalyst_storm", "Stormbound Catalyst", ItemKind.MATERIAL, tier = 4,
            buyPrice = 1500, sellPrice = 750, icon = "🌠",
            description = "Stormheart fused with a voidforged crystal. Required for TRANSCENDENT enhancement."),

        // ---- equipment: tools ----
        ItemDefinition("tool_pickaxe", "Journeyman's Pickaxe", ItemKind.EQUIPMENT, slot = EquipSlot.TOOL,
            tier = 1, baseStats = CombatStats(attack = 1), maxDurability = 100,
            stackable = false, buyPrice = 80, sellPrice = 30, icon = "⛏️",
            description = "Mines 25% faster. Equip to your tool slot.", enhanceable = true,
            gatheringSkill = "mining", gatheringSpeedMultiplier = 1.25),
        ItemDefinition("tool_fishing_rod", "Stout Fishing Rod", ItemKind.EQUIPMENT, slot = EquipSlot.TOOL,
            tier = 1, baseStats = CombatStats(attack = 1), maxDurability = 90,
            stackable = false, buyPrice = 0, sellPrice = 40, icon = "🎣",
            description = "Fishes 25% faster. A reassuring bend in every cast.", enhanceable = true,
            gatheringSkill = "fishing", gatheringSpeedMultiplier = 1.25),

        // ---- equipment: weapons ----
        ItemDefinition("sword_bronze", "Bronze Sword", ItemKind.EQUIPMENT, slot = EquipSlot.MAIN_WEAPON,
            tier = 1, baseStats = CombatStats(attack = 8, accuracy = 5), maxDurability = 80,
            stackable = false, buyPrice = 0, sellPrice = 30, icon = "⚔️",
            description = "Your first real blade, forged from iron you mined.", enhanceable = true),
        ItemDefinition("sword_steel", "Steel Sword", ItemKind.EQUIPMENT, slot = EquipSlot.MAIN_WEAPON,
            tier = 2, baseStats = CombatStats(attack = 18, accuracy = 8), maxDurability = 110,
            stackable = false, buyPrice = 900, sellPrice = 350, icon = "🗡️",
            description = "Tempered steel. A genuine upgrade.", enhanceable = true),
        ItemDefinition("shield_oak", "Oak Shield", ItemKind.EQUIPMENT, slot = EquipSlot.SECONDARY_WEAPON,
            tier = 1, baseStats = CombatStats(defense = 6, accuracy = -2), maxDurability = 120,
            stackable = false, buyPrice = 0, sellPrice = 50, icon = "🪓",
            description = "Oak banded with rope. Blocks what the sword cannot.", enhanceable = true),

        // ---- equipment: armor ----
        ItemDefinition("armor_hide", "Hide Armor", ItemKind.EQUIPMENT, slot = EquipSlot.CHEST,
            tier = 1, baseStats = CombatStats(defense = 4, maxHp = 20), maxDurability = 70,
            stackable = false, buyPrice = 0, sellPrice = 25, icon = "🦺",
            description = "Wolf hide stitched over a lumber frame.", enhanceable = true),
        ItemDefinition("helmet_hide", "Hide Hood", ItemKind.EQUIPMENT, slot = EquipSlot.HELMET,
            tier = 1, baseStats = CombatStats(defense = 2, maxHp = 8), maxDurability = 60,
            stackable = false, buyPrice = 0, sellPrice = 18, icon = "🎩",
            description = "Warm and vaguely intimidating.", enhanceable = true),

        // ---- potions ----
        ItemDefinition("potion_lesser", "Lesser Vitality Draft", ItemKind.CONSUMABLE,
            buyPrice = 50, sellPrice = 20, icon = "🧪", healAmount = 50,
            description = "Restores 50 health."),

        // ---- enhancement & repair consumables ----
        ItemDefinition("oil_preservation", "Oil of Preservation", ItemKind.CONSUMABLE,
            buyPrice = 150, sellPrice = 60, icon = "🫗",
            description = "Prevents an enhancement failure from downgrading your item."),
        ItemDefinition("ward_of_stability", "Ward of Stability", ItemKind.CONSUMABLE,
            buyPrice = 420, sellPrice = 170, icon = "🛡️",
            description = "Fully negates an enhancement failure — no downgrade, no durability loss."),
        ItemDefinition("repair_kit", "Repair Kit", ItemKind.CONSUMABLE,
            buyPrice = 40, sellPrice = 15, icon = "🔧",
            description = "Restores durability to a damaged item."),
        ItemDefinition("bread", "Bread", ItemKind.CONSUMABLE,
            buyPrice = 30, sellPrice = 12, icon = "🍞", healAmount = 25,
            description = "Restores 25 health. Warmed by the oven and simple faith."),
        ItemDefinition("dried_fish", "Dried River Fish", ItemKind.CONSUMABLE,
            buyPrice = 24, sellPrice = 10, icon = "🥓", healAmount = 18,
            description = "Restores 18 health. Keeps for the trail."),

        // ================= PACK 01 — OUTER REACHES =================

        // ---- Cindervale: raw resources ----
        ItemDefinition("ore_cinder", "Cinder Ore", ItemKind.RESOURCE, tier = 2,
            buyPrice = 14, sellPrice = 7, icon = "🪨",
            description = "Dense, slow-burning ore veined with old fire."),
        ItemDefinition("emberglass", "Emberglass", ItemKind.RESOURCE, tier = 2,
            buyPrice = 30, sellPrice = 15, icon = "🔮",
            description = "Buried glass that still glows at dusk. The heart of the glass country."),
        ItemDefinition("sootwood", "Sootwood", ItemKind.RESOURCE, tier = 2,
            buyPrice = 12, sellPrice = 6, icon = "🪵",
            description = "Blackened timber, seasoned in smoke."),
        ItemDefinition("ashfish", "Ashfish", ItemKind.RESOURCE, tier = 2,
            buyPrice = 12, sellPrice = 5, icon = "🐟",
            description = "A pale fish that feeds in warm shallows."),
        ItemDefinition("saltash", "Saltash", ItemKind.RESOURCE, tier = 2,
            buyPrice = 10, sellPrice = 4, icon = "🧂",
            description = "Crusted salt raked from the ash flats."),
        ItemDefinition("ashgrain", "Ashgrain", ItemKind.RESOURCE, tier = 2,
            buyPrice = 12, sellPrice = 5, icon = "🌾",
            description = "Hardy grain that thrives in ashen soil."),

        // ---- Cindervale: processed materials ----
        ItemDefinition("cinder_fragment", "Cinder Fragment", ItemKind.MATERIAL, tier = 2,
            buyPrice = 28, sellPrice = 14, icon = "⚙️",
            description = "Crushed cinder ore, glowing faintly."),
        ItemDefinition("cinder_ingot", "Cinder Ingot", ItemKind.MATERIAL, tier = 2,
            buyPrice = 60, sellPrice = 30, icon = "🟧",
            description = "A cast ingot that holds heat long after the fire dies."),
        ItemDefinition("cinder_steel", "Cinder Steel", ItemKind.MATERIAL, tier = 2,
            buyPrice = 300, sellPrice = 150, icon = "🔶",
            description = "Steel alloyed with cinder ore. The backbone of Cindervale forging."),
        ItemDefinition("glass_shard", "Glass Shard", ItemKind.MATERIAL, tier = 2,
            buyPrice = 60, sellPrice = 30, icon = "💠",
            description = "Worked emberglass. Sharp, warm, and endlessly reusable."),
        ItemDefinition("soot_lumber", "Soot Lumber", ItemKind.MATERIAL, tier = 2,
            buyPrice = 26, sellPrice = 13, icon = "🟫",
            description = "Straight, smoke-cured planks that do not warp."),
        ItemDefinition("ash_flour", "Ash Flour", ItemKind.MATERIAL, tier = 2,
            buyPrice = 24, sellPrice = 12, icon = "🌫️",
            description = "Milled ashgrain with a faint mineral tang."),

        // ---- Cindervale: consumables ----
        ItemDefinition("ashcured_fish", "Ashcured Fish", ItemKind.CONSUMABLE, tier = 2,
            buyPrice = 40, sellPrice = 18, icon = "🥓", healAmount = 22,
            description = "Restores 22 health. Preserved in saltash."),
        ItemDefinition("hearth_bread", "Hearth Bread", ItemKind.CONSUMABLE, tier = 2,
            buyPrice = 60, sellPrice = 26, icon = "🍞", healAmount = 30,
            description = "Restores 30 health. Baked in the embers themselves."),
        ItemDefinition("salted_boar", "Salted Boar", ItemKind.CONSUMABLE, tier = 2,
            buyPrice = 55, sellPrice = 24, icon = "🥩", healAmount = 25,
            description = "Restores 25 health. Brined and slow-roasted."),
        ItemDefinition("ember_salve", "Ember Salve", ItemKind.CONSUMABLE, tier = 2,
            buyPrice = 120, sellPrice = 50, icon = "🫗", healAmount = 60,
            description = "Restores 60 health. Glass, leaf, and patient heat."),
        ItemDefinition("smoldering_draught", "Smoldering Draught", ItemKind.CONSUMABLE, tier = 2,
            buyPrice = 100, sellPrice = 42, icon = "🧪", healAmount = 50,
            description = "Restores 50 health. Burns bright going down."),
        ItemDefinition("ward_cinders", "Ward of Cinders", ItemKind.CONSUMABLE, tier = 2,
            buyPrice = 700, sellPrice = 300, icon = "🛡️",
            description = "Fully negates an enhancement failure — no downgrade, no durability loss. Crafted in the glass country."),

        // ---- Cindervale: boss material ----
        ItemDefinition("cinder_core", "Cinder Core", ItemKind.MATERIAL, tier = 2,
            buyPrice = 350, sellPrice = 175, icon = "🔥",
            description = "The cooled heart of the Ash Sovereign. Still ticking."),

        // ---- Cindervale: equipment (T2.5) ----
        ItemDefinition("sword_cinder", "Cinder Sword", ItemKind.EQUIPMENT, slot = EquipSlot.MAIN_WEAPON,
            tier = 2, baseStats = CombatStats(attack = 26, accuracy = 9), maxDurability = 120,
            stackable = false, buyPrice = 1200, sellPrice = 480, icon = "🗡️",
            description = "Tempered in ash and quenched in shadow.", enhanceable = true),
        ItemDefinition("bow_cinder", "Cinder Longbow", ItemKind.EQUIPMENT, slot = EquipSlot.SECONDARY_WEAPON,
            tier = 2, baseStats = CombatStats(attack = 10, accuracy = 14, critChance = 10, critMultiplier = 1.6), maxDurability = 100,
            stackable = false, buyPrice = 900, sellPrice = 360, icon = "🏹",
            description = "A bow of soot-lumber and rope that sings on release.", enhanceable = true),
        ItemDefinition("shield_ashbark", "Ashbark Shield", ItemKind.EQUIPMENT, slot = EquipSlot.SECONDARY_WEAPON,
            tier = 2, baseStats = CombatStats(defense = 10, accuracy = -1), maxDurability = 150,
            stackable = false, buyPrice = 700, sellPrice = 280, icon = "🛡️",
            description = "Charred oak, banded in rope. Holds against the hot wind.", enhanceable = true),
        ItemDefinition("pickaxe_cinder", "Cinder Pickaxe", ItemKind.EQUIPMENT, slot = EquipSlot.TOOL,
            tier = 2, baseStats = CombatStats(attack = 3), maxDurability = 130,
            stackable = false, buyPrice = 700, sellPrice = 280, icon = "⛏️",
            description = "Mines 30% faster. The head drinks the heat.", enhanceable = true,
            gatheringSkill = "mining", gatheringSpeedMultiplier = 1.30),
        ItemDefinition("gloves_ashbark", "Ashbark Gloves", ItemKind.EQUIPMENT, slot = EquipSlot.GLOVES,
            tier = 2, baseStats = CombatStats(defense = 3, maxHp = 10), maxDurability = 90,
            stackable = false, buyPrice = 450, sellPrice = 180, icon = "🧤",
            description = "Smoked-leather gloves that grip even in ash.", enhanceable = true),
        ItemDefinition("boots_ashbark", "Ashbark Boots", ItemKind.EQUIPMENT, slot = EquipSlot.BOOTS,
            tier = 2, baseStats = CombatStats(defense = 3, evasion = 3), maxDurability = 90,
            stackable = false, buyPrice = 450, sellPrice = 180, icon = "👢",
            description = "High boots that shrug off the cinder-wind.", enhanceable = true),
        ItemDefinition("chest_cinder", "Cinder Breastplate", ItemKind.EQUIPMENT, slot = EquipSlot.CHEST,
            tier = 2, baseStats = CombatStats(defense = 9, maxHp = 45), maxDurability = 120,
            stackable = false, buyPrice = 900, sellPrice = 360, icon = "🦺",
            description = "Riveted cinder steel over a hide lining.", enhanceable = true),
        ItemDefinition("hood_cinder", "Cinder Hood", ItemKind.EQUIPMENT, slot = EquipSlot.HELMET,
            tier = 2, baseStats = CombatStats(defense = 5, maxHp = 20), maxDurability = 90,
            stackable = false, buyPrice = 550, sellPrice = 220, icon = "🎩",
            description = "A hood that keeps the smoke out of your eyes.", enhanceable = true),
        ItemDefinition("ring_ember", "Ember Ring", ItemKind.EQUIPMENT, slot = EquipSlot.ACCESSORY_1,
            tier = 2, baseStats = CombatStats(attack = 4, critChance = 4), maxDurability = 80,
            stackable = false, buyPrice = 650, sellPrice = 260, icon = "💍",
            description = "Emberglass set in cinder silver. Warms the hand that fights.", enhanceable = true),
        ItemDefinition("amulet_ashveil", "Ashveil Amulet", ItemKind.EQUIPMENT, slot = EquipSlot.ACCESSORY_2,
            tier = 2, baseStats = CombatStats(defense = 3, maxHp = 25), maxDurability = 80,
            stackable = false, buyPrice = 650, sellPrice = 260, icon = "📿",
            description = "A pendant of ash-glass that steadies the heart.", enhanceable = true),

        // ---- Stormreach deepening: resources & materials ----
        ItemDefinition("ore_storm", "Storm Ore", ItemKind.RESOURCE, tier = 3,
            buyPrice = 26, sellPrice = 12, icon = "⛰️",
            description = "Iron shot through with living lightning."),
        ItemDefinition("thunderwood", "Thunderwood", ItemKind.RESOURCE, tier = 3,
            buyPrice = 22, sellPrice = 10, icon = "🌲",
            description = "Wood that remembers every storm that passed through it."),
        ItemDefinition("stormgrain", "Stormgrain", ItemKind.RESOURCE, tier = 3,
            buyPrice = 20, sellPrice = 9, icon = "🌾",
            description = "Bristling grain that grows in the thunder-shadow."),
        ItemDefinition("stormcrystal", "Stormcrystal", ItemKind.RESOURCE, tier = 3,
            buyPrice = 60, sellPrice = 28, icon = "🔷",
            description = "Frozen lightning. Rare even in the storm country."),
        ItemDefinition("storm_fragment", "Storm Fragment", ItemKind.MATERIAL, tier = 3,
            buyPrice = 52, sellPrice = 26, icon = "⚙️",
            description = "Crushed storm ore, crackling at the edges."),
        ItemDefinition("storm_ingot", "Storm Ingot", ItemKind.MATERIAL, tier = 3,
            buyPrice = 110, sellPrice = 55, icon = "🟨",
            description = "An ingot that hums with a low, steady charge."),
        ItemDefinition("storm_steel", "Storm Steel", ItemKind.MATERIAL, tier = 3,
            buyPrice = 560, sellPrice = 280, icon = "🟡",
            description = "Steel alloyed with storm ore and cinder steel. Weather-forged."),
        ItemDefinition("storm_lumber", "Storm Lumber", ItemKind.MATERIAL, tier = 3,
            buyPrice = 48, sellPrice = 24, icon = "🟠",
            description = "Seasoned thunderwood that steadies under pressure."),
        ItemDefinition("storm_flour", "Storm Flour", ItemKind.MATERIAL, tier = 3,
            buyPrice = 44, sellPrice = 22, icon = "🌾",
            description = "Milled stormgrain with a faint electric shimmer."),
        ItemDefinition("storm_bread", "Storm Bread", ItemKind.CONSUMABLE, tier = 3,
            buyPrice = 90, sellPrice = 38, icon = "🍞", healAmount = 32,
            description = "Restores 32 health. It crackles faintly as you eat it."),

        // ---- Frostreach: raw resources ----
        ItemDefinition("ore_frost", "Frost Ore", ItemKind.RESOURCE, tier = 3,
            buyPrice = 30, sellPrice = 14, icon = "❄️",
            description = "Pale ore that holds the cold like a promise."),
        ItemDefinition("icewood", "Icewood", ItemKind.RESOURCE, tier = 3,
            buyPrice = 26, sellPrice = 12, icon = "🪵",
            description = "Frozen timber that rings like glass when cut."),
        ItemDefinition("glacefish", "Glacefish", ItemKind.RESOURCE, tier = 3,
            buyPrice = 22, sellPrice = 10, icon = "🐟",
            description = "A fish of the frozen mere, kept cold by habit."),
        ItemDefinition("frostmoss", "Frostmoss", ItemKind.RESOURCE, tier = 3,
            buyPrice = 24, sellPrice = 11, icon = "🌿",
            description = "A blue-grey moss that only grows above the snow line."),
        ItemDefinition("frostvein", "Frostvein Crystal", ItemKind.RESOURCE, tier = 3,
            buyPrice = 90, sellPrice = 42, icon = "💎",
            description = "A crystal that drinks heat. The secret of the ADVANCED forge."),

        // ---- Frostreach: processed materials ----
        ItemDefinition("frost_fragment", "Frost Fragment", ItemKind.MATERIAL, tier = 3,
            buyPrice = 60, sellPrice = 30, icon = "⚙️",
            description = "Crushed frost ore that steams in warm air."),
        ItemDefinition("frost_ingot", "Frost Ingot", ItemKind.MATERIAL, tier = 3,
            buyPrice = 126, sellPrice = 63, icon = "🟦",
            description = "A cold-cast ingot. Handle with gloves."),
        ItemDefinition("froststeel", "Froststeel", ItemKind.MATERIAL, tier = 3,
            buyPrice = 640, sellPrice = 320, icon = "🔷",
            description = "Frost iron alloyed with cinder steel. It never dulls."),
        ItemDefinition("frost_lumber", "Frost Lumber", ItemKind.MATERIAL, tier = 3,
            buyPrice = 52, sellPrice = 26, icon = "🟩",
            description = "Icewood planks, trued against the glacier."),

        // ---- Frostreach: consumables ----
        ItemDefinition("smoked_glacefish", "Smoked Glacefish", ItemKind.CONSUMABLE, tier = 3,
            buyPrice = 70, sellPrice = 30, icon = "🥓", healAmount = 30,
            description = "Restores 30 health. Cold-caught, warm-smoked."),
        ItemDefinition("frost_draught", "Frost Draught", ItemKind.CONSUMABLE, tier = 3,
            buyPrice = 150, sellPrice = 64, icon = "🧪", healAmount = 70,
            description = "Restores 70 health. Frostmoss, emberglass, and nerve."),
        ItemDefinition("ward_frost", "Ward of Frost", ItemKind.CONSUMABLE, tier = 3,
            buyPrice = 900, sellPrice = 400, icon = "🛡️",
            description = "Fully negates an enhancement failure — no downgrade, no durability loss. Sealed in glacier ice."),

        // ---- Frostreach: equipment (T3.5) ----
        ItemDefinition("frostblade", "Frostblade", ItemKind.EQUIPMENT, slot = EquipSlot.MAIN_WEAPON,
            tier = 3, baseStats = CombatStats(attack = 34, accuracy = 11), maxDurability = 150,
            stackable = false, buyPrice = 2600, sellPrice = 1050, icon = "🗡️",
            description = "Froststeel forged in a foundry that breathes cold.", enhanceable = true),
        ItemDefinition("frost_shield", "Frost Shield", ItemKind.EQUIPMENT, slot = EquipSlot.SECONDARY_WEAPON,
            tier = 3, baseStats = CombatStats(defense = 14, accuracy = -1), maxDurability = 180,
            stackable = false, buyPrice = 1500, sellPrice = 600, icon = "🛡️",
            description = "A shield of frost_lumber that swallows the wind.", enhanceable = true),
        ItemDefinition("frost_gauntlets", "Frost Gauntlets", ItemKind.EQUIPMENT, slot = EquipSlot.GLOVES,
            tier = 3, baseStats = CombatStats(defense = 5, attack = 3), maxDurability = 120,
            stackable = false, buyPrice = 900, sellPrice = 360, icon = "🧤",
            description = "Plated gloves that keep a grip in the cold.", enhanceable = true),
        ItemDefinition("frostgreave_boots", "Frostgreave Boots", ItemKind.EQUIPMENT, slot = EquipSlot.BOOTS,
            tier = 3, baseStats = CombatStats(defense = 5, evasion = 5), maxDurability = 120,
            stackable = false, buyPrice = 900, sellPrice = 360, icon = "👢",
            description = "Tall boots that leave no print in the snow.", enhanceable = true),
        ItemDefinition("frostplate", "Frostplate", ItemKind.EQUIPMENT, slot = EquipSlot.CHEST,
            tier = 3, baseStats = CombatStats(defense = 14, maxHp = 70), maxDurability = 150,
            stackable = false, buyPrice = 1800, sellPrice = 720, icon = "🦺",
            description = "A breastplate of froststeel that never frosts over.", enhanceable = true),
        ItemDefinition("frost_hood", "Frost Hood", ItemKind.EQUIPMENT, slot = EquipSlot.HELMET,
            tier = 3, baseStats = CombatStats(defense = 8, maxHp = 30), maxDurability = 110,
            stackable = false, buyPrice = 1000, sellPrice = 400, icon = "🎩",
            description = "A hood lined with frostmoss, warm and strange.", enhanceable = true),
        ItemDefinition("frostvein_ring", "Frostvein Ring", ItemKind.EQUIPMENT, slot = EquipSlot.ACCESSORY_1,
            tier = 3, baseStats = CombatStats(attack = 7, critChance = 6), maxDurability = 100,
            stackable = false, buyPrice = 1400, sellPrice = 560, icon = "💍",
            description = "A ring set with a single living frostvein.", enhanceable = true),
        ItemDefinition("icebound_amulet", "Icebound Amulet", ItemKind.EQUIPMENT, slot = EquipSlot.ACCESSORY_2,
            tier = 3, baseStats = CombatStats(defense = 5, maxHp = 40), maxDurability = 100,
            stackable = false, buyPrice = 1400, sellPrice = 560, icon = "📿",
            description = "An amulet of glass and frostvein that steadies breath.", enhanceable = true),
        ItemDefinition("pickaxe_frostforge", "Frostforge Pickaxe", ItemKind.EQUIPMENT, slot = EquipSlot.TOOL,
            tier = 3, baseStats = CombatStats(attack = 5), maxDurability = 160,
            stackable = false, buyPrice = 1400, sellPrice = 560, icon = "⛏️",
            description = "Mines 35% faster. The head never warms to the rock.", enhanceable = true,
            gatheringSkill = "mining", gatheringSpeedMultiplier = 1.35),
    ).associateBy { it.id }

    fun get(id: ItemId): ItemDefinition = all[id]
        ?: error("Unknown item def '$id' (content gap)")

    fun contains(id: ItemId): Boolean = all.containsKey(id)
    fun allItems(): List<ItemDefinition> = all.values.sortedBy { it.tier }
}
