package com.projecteternal.content

import com.projecteternal.model.ItemStack
import com.projecteternal.model.RecipeId

/**
 * Static processing/crafting recipe catalog. Processing recipes use the
 * PROCESSING skills; crafting recipes use the CRAFTING skills.
 */
object Recipes {
    private val all: Map<RecipeId, RecipeDefinition> = listOf(
        // ---- processing: ore -> fragments -> ingots -> alloys ----
        RecipeDefinition(
            id = "grind_iron", name = "Grind Iron Ore", skillId = "grinding",
            timeSeconds = 3,
            inputs = listOf(ItemStack("ore_iron", 1)),
            outputs = listOf(ItemStack("iron_fragment", 2)),
            xpPerCraft = 5,
            description = "Crush ore into fragments.",
        ),
        RecipeDefinition(
            id = "smelt_ingot", name = "Smelt Iron Ingot", skillId = "smelting",
            timeSeconds = 5,
            inputs = listOf(ItemStack("iron_fragment", 2)),
            outputs = listOf(ItemStack("iron_ingot", 1)),
            xpPerCraft = 7,
            description = "Fragments into an ingot.",
        ),
        RecipeDefinition(
            id = "refine_refined", name = "Refine Iron", skillId = "refining",
            timeSeconds = 8,
            inputs = listOf(ItemStack("iron_ingot", 2)),
            outputs = listOf(ItemStack("refined_iron", 1)),
            xpPerCraft = 18,
            description = "High-purity iron for advanced work.",
        ),
        RecipeDefinition(
            id = "refine_steel", name = "Forge Steel", skillId = "refining", skillLevelRequired = 2,
            timeSeconds = 12,
            inputs = listOf(ItemStack("refined_iron", 2), ItemStack("ore_coal", 1)),
            outputs = listOf(ItemStack("steel", 1)),
            xpPerCraft = 40,
            description = "Iron, coal and patience.",
        ),
        RecipeDefinition(
            id = "refine_catalyst", name = "Distill Stormbound Catalyst", skillId = "refining", skillLevelRequired = 5,
            timeSeconds = 20,
            inputs = listOf(ItemStack("core_storm", 1), ItemStack("crystal_advanced", 2)),
            outputs = listOf(ItemStack("catalyst_storm", 1)),
            xpPerCraft = 90,
            unlockToken = "recipe:refine_catalyst",
            description = "A stormheart core, stilled in voidforged crystal. The key to transcending.",
        ),
        RecipeDefinition(
            id = "heat_lumber", name = "Dry Lumber", skillId = "heating",
            timeSeconds = 3,
            inputs = listOf(ItemStack("wood", 1)),
            outputs = listOf(ItemStack("lumber", 1)),
            xpPerCraft = 4,
            description = "Seasoned, straight planks.",
        ),
        // ---- processing: harvest -> provisions ----
        RecipeDefinition(
            id = "dry_fish", name = "Dry River Carp", skillId = "drying",
            timeSeconds = 4,
            inputs = listOf(ItemStack("fish_carp", 1)),
            outputs = listOf(ItemStack("dried_fish", 1)),
            xpPerCraft = 6,
            description = "Salt, air and time make the catch last the winter.",
        ),
        RecipeDefinition(
            id = "mill_flour", name = "Mill Grain to Flour", skillId = "milling",
            timeSeconds = 3,
            inputs = listOf(ItemStack("grain", 1)),
            outputs = listOf(ItemStack("flour", 1)),
            xpPerCraft = 5,
            description = "The terraces give grain; the wheel gives flour.",
        ),
        // ---- crafting: tools & gear ----
        RecipeDefinition(
            id = "craft_rope", name = "Twist Hemp Rope", skillId = "carpentry",
            timeSeconds = 3,
            inputs = listOf(ItemStack("wood", 1)),
            outputs = listOf(ItemStack("rope", 1)),
            xpPerCraft = 5,
            description = "Twist, braid and pull until it holds.",
        ),
        RecipeDefinition(
            id = "craft_fishing_rod", name = "Build Stout Fishing Rod", skillId = "carpentry",
            skillLevelRequired = 1, timeSeconds = 6,
            inputs = listOf(ItemStack("wood", 1), ItemStack("rope", 1)),
            outputs = listOf(ItemStack("tool_fishing_rod", 1)),
            xpPerCraft = 10,
            unlockToken = "recipe:craft_fishing_rod",
            description = "A rod with spine enough for the river's best.",
        ),
        RecipeDefinition(
            id = "craft_shield_oak", name = "Band the Oak Shield", skillId = "carpentry",
            skillLevelRequired = 2, timeSeconds = 8,
            inputs = listOf(ItemStack("lumber", 2), ItemStack("rope", 1)),
            outputs = listOf(ItemStack("shield_oak", 1)),
            xpPerCraft = 14,
            unlockToken = "recipe:craft_shield_oak",
            description = "Oak and rope, fitted to your arm.",
        ),
        RecipeDefinition(
            id = "craft_machinery_part", name = "Fabricate Machinery Part", skillId = "engineering",
            timeSeconds = 10,
            inputs = listOf(ItemStack("steel", 1), ItemStack("lumber", 1)),
            outputs = listOf(ItemStack("machinery_part", 1)),
            xpPerCraft = 30,
            description = "Precision tolerances, hold a breath and strike.",
        ),
        RecipeDefinition(
            id = "shape_ward", name = "Shape Ward of Stability", skillId = "engineering",
            skillLevelRequired = 2, timeSeconds = 12,
            inputs = listOf(ItemStack("crystal_advanced", 1), ItemStack("steel", 1)),
            outputs = listOf(ItemStack("ward_of_stability", 1)),
            xpPerCraft = 45,
            unlockToken = "recipe:shape_ward",
            description = "Voidforged crystal bound in steel, stilling chaos itself.",
        ),
        // ---- crafting: consumables ----
        RecipeDefinition(
            id = "cook_roast", name = "Roast Wolf Meat", skillId = "cooking",
            timeSeconds = 3,
            inputs = listOf(ItemStack("meat_wolf", 1)),
            outputs = listOf(ItemStack("roasted_meat", 1)),
            xpPerCraft = 4,
            description = "Tastes like victory, slightly gamey.",
        ),
        RecipeDefinition(
            id = "bake_bread", name = "Bake Bread", skillId = "cooking",
            timeSeconds = 5,
            inputs = listOf(ItemStack("flour", 1)),
            outputs = listOf(ItemStack("bread", 1)),
            xpPerCraft = 8,
            description = "Flour, water and the patience of stone ovens.",
        ),
        // ---- crafting: weapons & armor ----
        RecipeDefinition(
            id = "craft_sword_bronze", name = "Forge Bronze Sword", skillId = "blacksmithing",
            timeSeconds = 6,
            inputs = listOf(ItemStack("iron_ingot", 2), ItemStack("wood", 1)),
            outputs = listOf(ItemStack("sword_bronze", 1)),
            xpPerCraft = 12,
            unlockToken = "recipe:sword_bronze",
            description = "Your first blade.",
        ),
        RecipeDefinition(
            id = "craft_sword_steel", name = "Forge Steel Sword", skillId = "blacksmithing",
            skillLevelRequired = 4, timeSeconds = 15,
            inputs = listOf(ItemStack("steel", 2), ItemStack("lumber", 1)),
            outputs = listOf(ItemStack("sword_steel", 1)),
            xpPerCraft = 60,
            unlockToken = "recipe:sword_steel",
            description = "A real soldier's weapon.",
        ),
        RecipeDefinition(
            id = "craft_armor_hide", name = "Stitch Hide Armor", skillId = "armorcraft",
            timeSeconds = 5,
            inputs = listOf(ItemStack("pelt_wolf", 3), ItemStack("wood", 1)),
            outputs = listOf(ItemStack("armor_hide", 1)),
            xpPerCraft = 10,
            description = "Fur and lumber, held together by willpower.",
        ),
        RecipeDefinition(
            id = "craft_helmet_hide", name = "Stitch Hide Hood", skillId = "armorcraft",
            timeSeconds = 4,
            inputs = listOf(ItemStack("pelt_wolf", 2)),
            outputs = listOf(ItemStack("helmet_hide", 1)),
            xpPerCraft = 8,
            description = "Keeps the rain out of your ears.",
        ),
        RecipeDefinition(
            id = "craft_pickaxe", name = "Forge Journeyman's Pickaxe", skillId = "blacksmithing",
            skillLevelRequired = 1, timeSeconds = 8,
            inputs = listOf(ItemStack("iron_ingot", 2), ItemStack("wood", 2)),
            outputs = listOf(ItemStack("tool_pickaxe", 1)),
            xpPerCraft = 14,
            description = "A proper mining tool.",
        ),
        // ---- crafting: consumables ----
        RecipeDefinition(
            id = "brew_potion", name = "Brew Lesser Vitality Draft", skillId = "alchemy",
            timeSeconds = 5,
            inputs = listOf(ItemStack("herb_brightleaf", 2)),
            outputs = listOf(ItemStack("potion_lesser", 1)),
            xpPerCraft = 6,
            description = "Brightleaf, water, fire.",
        ),

        // ================= PACK 01 — OUTER REACHES =================

        // ---- Cindervale: processing (region:cindervale) ----
        RecipeDefinition(
            id = "grind_cinder", name = "Grind Cinder Ore", skillId = "grinding",
            timeSeconds = 4,
            inputs = listOf(ItemStack("ore_cinder", 1)),
            outputs = listOf(ItemStack("cinder_fragment", 2)),
            xpPerCraft = 9,
            unlockToken = "region:cindervale",
            description = "Crush cinder ore into glowing fragments.",
        ),
        RecipeDefinition(
            id = "smelt_cinder", name = "Smelt Cinder Ingot", skillId = "smelting",
            timeSeconds = 6,
            inputs = listOf(ItemStack("cinder_fragment", 2)),
            outputs = listOf(ItemStack("cinder_ingot", 1)),
            xpPerCraft = 12,
            unlockToken = "region:cindervale",
            description = "Fragments into a warm ingot.",
        ),
        RecipeDefinition(
            id = "refine_cinder_steel", name = "Forge Cinder Steel", skillId = "refining", skillLevelRequired = 2,
            timeSeconds = 10,
            inputs = listOf(ItemStack("cinder_ingot", 2), ItemStack("ore_coal", 1)),
            outputs = listOf(ItemStack("cinder_steel", 1)),
            xpPerCraft = 30,
            unlockToken = "region:cindervale",
            description = "Cinder ingots, coal, and a furnace that never cools.",
        ),
        RecipeDefinition(
            id = "vitrify_glass", name = "Vitrify Emberglass", skillId = "heating",
            timeSeconds = 5,
            inputs = listOf(ItemStack("emberglass", 1)),
            outputs = listOf(ItemStack("glass_shard", 1)),
            xpPerCraft = 10,
            unlockToken = "region:cindervale",
            description = "Heat emberglass until it runs clear.",
        ),
        RecipeDefinition(
            id = "season_soot_lumber", name = "Season Sootwood", skillId = "heating",
            timeSeconds = 4,
            inputs = listOf(ItemStack("sootwood", 1)),
            outputs = listOf(ItemStack("soot_lumber", 1)),
            xpPerCraft = 8,
            unlockToken = "region:cindervale",
            description = "Smoke-true planks that do not warp.",
        ),
        RecipeDefinition(
            id = "mill_ash_flour", name = "Mill Ash Flour", skillId = "milling",
            timeSeconds = 4,
            inputs = listOf(ItemStack("ashgrain", 1)),
            outputs = listOf(ItemStack("ash_flour", 1)),
            xpPerCraft = 9,
            unlockToken = "region:cindervale",
            description = "The wheel turns; the grain becomes storable.",
        ),
        RecipeDefinition(
            id = "dry_ashfish", name = "Ashcure River Fish", skillId = "drying",
            timeSeconds = 4,
            inputs = listOf(ItemStack("ashfish", 1), ItemStack("saltash", 1)),
            outputs = listOf(ItemStack("ashcured_fish", 1)),
            xpPerCraft = 8,
            unlockToken = "region:cindervale",
            description = "Saltash and warm air make the catch keep.",
        ),

        // ---- Cindervale: food & provisions (region:cindervale) ----
        RecipeDefinition(
            id = "cook_hearth_bread", name = "Bake Hearth Bread", skillId = "cooking",
            timeSeconds = 6,
            inputs = listOf(ItemStack("ash_flour", 1), ItemStack("saltash", 1)),
            outputs = listOf(ItemStack("hearth_bread", 1)),
            xpPerCraft = 12,
            unlockToken = "region:cindervale",
            description = "Baked in the embers of the ash country.",
        ),
        RecipeDefinition(
            id = "cook_salted_boar", name = "Salt the Boar", skillId = "cooking",
            timeSeconds = 5,
            inputs = listOf(ItemStack("meat_boar", 1), ItemStack("saltash", 1)),
            outputs = listOf(ItemStack("salted_boar", 1)),
            xpPerCraft = 10,
            unlockToken = "region:cindervale",
            description = "Brined boar that keeps for the high road.",
        ),

        // ---- Cindervale: glass country (recipe:glasswork) ----
        RecipeDefinition(
            id = "alch_ember_salve", name = "Blend Ember Salve", skillId = "alchemy", skillLevelRequired = 2,
            timeSeconds = 7,
            inputs = listOf(ItemStack("glass_shard", 1), ItemStack("herb_brightleaf", 1)),
            outputs = listOf(ItemStack("ember_salve", 1)),
            xpPerCraft = 14,
            unlockToken = "recipe:glasswork",
            description = "Glass, leaf, and patient heat.",
        ),
        RecipeDefinition(
            id = "alch_smoldering_draught", name = "Brew Smoldering Draught", skillId = "alchemy", skillLevelRequired = 2,
            timeSeconds = 7,
            inputs = listOf(ItemStack("glass_shard", 1), ItemStack("ashgrain", 1)),
            outputs = listOf(ItemStack("smoldering_draught", 1)),
            xpPerCraft = 14,
            unlockToken = "recipe:glasswork",
            description = "Burns bright going down.",
        ),
        RecipeDefinition(
            id = "eng_ward_cinders", name = "Shape Ward of Cinders", skillId = "engineering", skillLevelRequired = 3,
            timeSeconds = 14,
            inputs = listOf(ItemStack("glass_shard", 1), ItemStack("cinder_steel", 1)),
            outputs = listOf(ItemStack("ward_cinders", 1)),
            xpPerCraft = 60,
            unlockToken = "recipe:glasswork",
            description = "Emberglass bound in cinder steel, stilling the shatter.",
        ),
        RecipeDefinition(
            id = "craft_bow_cinder", name = "String the Cinder Longbow", skillId = "carpentry", skillLevelRequired = 3,
            timeSeconds = 12,
            inputs = listOf(ItemStack("soot_lumber", 2), ItemStack("rope", 1)),
            outputs = listOf(ItemStack("bow_cinder", 1)),
            xpPerCraft = 55,
            unlockToken = "recipe:glasswork",
            description = "Soot-lumber, rope, and a steady hand.",
        ),

        // ---- Cindervale: cinder gear (recipe:cinder_gear) ----
        RecipeDefinition(
            id = "craft_gloves_ashbark", name = "Stitch Ashbark Gloves", skillId = "armorcraft", skillLevelRequired = 2,
            timeSeconds = 8,
            inputs = listOf(ItemStack("pelt_boar", 1), ItemStack("soot_lumber", 1)),
            outputs = listOf(ItemStack("gloves_ashbark", 1)),
            xpPerCraft = 35,
            unlockToken = "recipe:cinder_gear",
            description = "Boar hide over soot-lumber fingers.",
        ),
        RecipeDefinition(
            id = "craft_boots_ashbark", name = "Stitch Ashbark Boots", skillId = "armorcraft", skillLevelRequired = 2,
            timeSeconds = 8,
            inputs = listOf(ItemStack("pelt_boar", 1), ItemStack("soot_lumber", 1)),
            outputs = listOf(ItemStack("boots_ashbark", 1)),
            xpPerCraft = 35,
            unlockToken = "recipe:cinder_gear",
            description = "High boots that shrug off the cinder-wind.",
        ),
        RecipeDefinition(
            id = "craft_chest_cinder", name = "Rivet the Cinder Breastplate", skillId = "blacksmithing", skillLevelRequired = 3,
            timeSeconds = 15,
            inputs = listOf(ItemStack("cinder_steel", 1), ItemStack("pelt_boar", 1)),
            outputs = listOf(ItemStack("chest_cinder", 1)),
            xpPerCraft = 70,
            unlockToken = "recipe:cinder_gear",
            description = "Riveted cinder steel over a hide lining.",
        ),
        RecipeDefinition(
            id = "craft_hood_cinder", name = "Stitch the Cinder Hood", skillId = "armorcraft", skillLevelRequired = 3,
            timeSeconds = 12,
            inputs = listOf(ItemStack("cinder_steel", 1), ItemStack("pelt_wolf", 1)),
            outputs = listOf(ItemStack("hood_cinder", 1)),
            xpPerCraft = 55,
            unlockToken = "recipe:cinder_gear",
            description = "A hood that keeps the smoke out of your eyes.",
        ),
        RecipeDefinition(
            id = "craft_shield_ashbark", name = "Band the Ashbark Shield", skillId = "carpentry", skillLevelRequired = 3,
            timeSeconds = 12,
            inputs = listOf(ItemStack("soot_lumber", 2), ItemStack("rope", 1)),
            outputs = listOf(ItemStack("shield_ashbark", 1)),
            xpPerCraft = 55,
            unlockToken = "recipe:cinder_gear",
            description = "Charred oak, banded in rope.",
        ),
        RecipeDefinition(
            id = "craft_pickaxe_cinder", name = "Forge the Cinder Pickaxe", skillId = "blacksmithing", skillLevelRequired = 3,
            timeSeconds = 14,
            inputs = listOf(ItemStack("cinder_steel", 1), ItemStack("soot_lumber", 2)),
            outputs = listOf(ItemStack("pickaxe_cinder", 1)),
            xpPerCraft = 60,
            unlockToken = "recipe:cinder_gear",
            description = "A mining tool that drinks the heat.",
        ),

        // ---- Cindervale: weapons & jewelry (quest tokens) ----
        RecipeDefinition(
            id = "craft_sword_cinder", name = "Forge the Cinder Sword", skillId = "blacksmithing", skillLevelRequired = 3,
            timeSeconds = 15,
            inputs = listOf(ItemStack("cinder_steel", 2), ItemStack("soot_lumber", 1)),
            outputs = listOf(ItemStack("sword_cinder", 1)),
            xpPerCraft = 70,
            unlockToken = "recipe:sword_cinder",
            description = "Tempered in ash, quenched in shadow.",
        ),
        RecipeDefinition(
            id = "craft_ring_ember", name = "Set the Ember Ring", skillId = "jewelry",
            timeSeconds = 10,
            inputs = listOf(ItemStack("emberglass", 1), ItemStack("glass_shard", 1)),
            outputs = listOf(ItemStack("ring_ember", 1)),
            xpPerCraft = 45,
            unlockToken = "recipe:jewelry",
            description = "Emberglass set in cinder silver.",
        ),
        RecipeDefinition(
            id = "craft_amulet_ashveil", name = "Cut the Ashveil Amulet", skillId = "jewelry", skillLevelRequired = 3,
            timeSeconds = 12,
            inputs = listOf(ItemStack("emberglass", 1), ItemStack("cinder_steel", 1)),
            outputs = listOf(ItemStack("amulet_ashveil", 1)),
            xpPerCraft = 60,
            unlockToken = "recipe:jewelry",
            description = "A pendant of ash-glass that steadies the heart.",
        ),

        // ---- Stormreach deepening: processing (region:stormreach) ----
        RecipeDefinition(
            id = "grind_storm", name = "Grind Storm Ore", skillId = "grinding", skillLevelRequired = 3,
            timeSeconds = 6,
            inputs = listOf(ItemStack("ore_storm", 1)),
            outputs = listOf(ItemStack("storm_fragment", 2)),
            xpPerCraft = 16,
            unlockToken = "region:stormreach",
            description = "Crush storm ore; mind the sparks.",
        ),
        RecipeDefinition(
            id = "smelt_storm", name = "Smelt Storm Ingot", skillId = "smelting", skillLevelRequired = 3,
            timeSeconds = 8,
            inputs = listOf(ItemStack("storm_fragment", 2)),
            outputs = listOf(ItemStack("storm_ingot", 1)),
            xpPerCraft = 22,
            unlockToken = "region:stormreach",
            description = "An ingot that hums with low charge.",
        ),
        RecipeDefinition(
            id = "refine_storm_steel", name = "Forge Storm Steel", skillId = "refining", skillLevelRequired = 3,
            timeSeconds = 14,
            inputs = listOf(ItemStack("storm_ingot", 2), ItemStack("cinder_steel", 1)),
            outputs = listOf(ItemStack("storm_steel", 1)),
            xpPerCraft = 60,
            unlockToken = "region:stormreach",
            description = "Storm ore and cinder steel, weather-forged.",
        ),
        RecipeDefinition(
            id = "season_storm_lumber", name = "Season Thunderwood", skillId = "heating", skillLevelRequired = 3,
            timeSeconds = 6,
            inputs = listOf(ItemStack("thunderwood", 1)),
            outputs = listOf(ItemStack("storm_lumber", 1)),
            xpPerCraft = 14,
            unlockToken = "region:stormreach",
            description = "Wood that steadies under pressure.",
        ),
        RecipeDefinition(
            id = "mill_storm_flour", name = "Mill Storm Flour", skillId = "milling", skillLevelRequired = 3,
            timeSeconds = 5,
            inputs = listOf(ItemStack("stormgrain", 1)),
            outputs = listOf(ItemStack("storm_flour", 1)),
            xpPerCraft = 12,
            unlockToken = "region:stormreach",
            description = "The wheel turns; the grain sparkles.",
        ),
        RecipeDefinition(
            id = "cook_storm_bread", name = "Bake Storm Bread", skillId = "cooking", skillLevelRequired = 3,
            timeSeconds = 6,
            inputs = listOf(ItemStack("storm_flour", 1), ItemStack("saltash", 1)),
            outputs = listOf(ItemStack("storm_bread", 1)),
            xpPerCraft = 14,
            unlockToken = "region:stormreach",
            description = "Baked where the squall can reach the oven.",
        ),
        RecipeDefinition(
            id = "eng_storm_ward", name = "Shape a Storm Ward", skillId = "engineering", skillLevelRequired = 3,
            timeSeconds = 14,
            inputs = listOf(ItemStack("stormcrystal", 1), ItemStack("storm_steel", 1)),
            outputs = listOf(ItemStack("ward_of_stability", 1)),
            xpPerCraft = 60,
            unlockToken = "region:stormreach",
            description = "Frozen lightning bound in storm steel. Stills the shatter.",
        ),

        // ---- Frostreach: processing (region:frostreach) ----
        RecipeDefinition(
            id = "grind_frost", name = "Grind Frost Ore", skillId = "grinding", skillLevelRequired = 3,
            timeSeconds = 6,
            inputs = listOf(ItemStack("ore_frost", 1)),
            outputs = listOf(ItemStack("frost_fragment", 2)),
            xpPerCraft = 18,
            unlockToken = "region:frostreach",
            description = "Crush frost ore; it steams in warm air.",
        ),
        RecipeDefinition(
            id = "smelt_frost", name = "Smelt Frost Ingot", skillId = "smelting", skillLevelRequired = 3,
            timeSeconds = 8,
            inputs = listOf(ItemStack("frost_fragment", 2)),
            outputs = listOf(ItemStack("frost_ingot", 1)),
            xpPerCraft = 24,
            unlockToken = "region:frostreach",
            description = "A cold-cast ingot. Handle with gloves.",
        ),
        RecipeDefinition(
            id = "refine_froststeel", name = "Forge Froststeel", skillId = "refining", skillLevelRequired = 4,
            timeSeconds = 16,
            inputs = listOf(ItemStack("frost_ingot", 2), ItemStack("cinder_steel", 1)),
            outputs = listOf(ItemStack("froststeel", 1)),
            xpPerCraft = 75,
            unlockToken = "region:frostreach",
            description = "Frost iron and cinder steel, joined in the cold.",
        ),
        RecipeDefinition(
            id = "season_frost_lumber", name = "Season Icewood", skillId = "heating", skillLevelRequired = 3,
            timeSeconds = 6,
            inputs = listOf(ItemStack("icewood", 1)),
            outputs = listOf(ItemStack("frost_lumber", 1)),
            xpPerCraft = 16,
            unlockToken = "region:frostreach",
            description = "Icewood planks, trued against the glacier.",
        ),
        RecipeDefinition(
            id = "dry_glacefish", name = "Smoke the Glacefish", skillId = "drying", skillLevelRequired = 3,
            timeSeconds = 5,
            inputs = listOf(ItemStack("glacefish", 1)),
            outputs = listOf(ItemStack("smoked_glacefish", 1)),
            xpPerCraft = 14,
            unlockToken = "region:frostreach",
            description = "Cold-caught, warm-smoked.",
        ),
        RecipeDefinition(
            id = "alch_frost_draught", name = "Brew Frost Draught", skillId = "alchemy", skillLevelRequired = 3,
            timeSeconds = 8,
            inputs = listOf(ItemStack("frostmoss", 1), ItemStack("emberglass", 1)),
            outputs = listOf(ItemStack("frost_draught", 1)),
            xpPerCraft = 30,
            unlockToken = "region:frostreach",
            description = "Frostmoss, emberglass, and nerve.",
        ),

        // ---- Frostreach: frostforge gear (recipe:frostforge) ----
        RecipeDefinition(
            id = "craft_frostblade", name = "Forge the Frostblade", skillId = "blacksmithing", skillLevelRequired = 4,
            timeSeconds = 18,
            inputs = listOf(ItemStack("froststeel", 2), ItemStack("frost_lumber", 1)),
            outputs = listOf(ItemStack("frostblade", 1)),
            xpPerCraft = 90,
            unlockToken = "recipe:frostforge",
            description = "Froststeel forged in a foundry that breathes cold.",
        ),
        RecipeDefinition(
            id = "craft_frost_shield", name = "Lay the Frost Shield", skillId = "carpentry", skillLevelRequired = 4,
            timeSeconds = 16,
            inputs = listOf(ItemStack("frost_lumber", 2), ItemStack("froststeel", 1)),
            outputs = listOf(ItemStack("frost_shield", 1)),
            xpPerCraft = 80,
            unlockToken = "recipe:frostforge",
            description = "A shield of frost lumber that swallows the wind.",
        ),
        RecipeDefinition(
            id = "craft_frost_gauntlets", name = "Forge Frost Gauntlets", skillId = "blacksmithing", skillLevelRequired = 4,
            timeSeconds = 14,
            inputs = listOf(ItemStack("froststeel", 1), ItemStack("pelt_boar", 1)),
            outputs = listOf(ItemStack("frost_gauntlets", 1)),
            xpPerCraft = 70,
            unlockToken = "recipe:frostforge",
            description = "Plated gloves that keep a grip in the cold.",
        ),
        RecipeDefinition(
            id = "craft_frostgreave_boots", name = "Lace Frostgreave Boots", skillId = "armorcraft", skillLevelRequired = 4,
            timeSeconds = 14,
            inputs = listOf(ItemStack("froststeel", 1), ItemStack("frost_lumber", 1)),
            outputs = listOf(ItemStack("frostgreave_boots", 1)),
            xpPerCraft = 70,
            unlockToken = "recipe:frostforge",
            description = "Tall boots that leave no print in the snow.",
        ),
        RecipeDefinition(
            id = "craft_frostplate", name = "Rivet the Frostplate", skillId = "blacksmithing", skillLevelRequired = 4,
            timeSeconds = 18,
            inputs = listOf(ItemStack("froststeel", 2), ItemStack("pelt_wolf", 1)),
            outputs = listOf(ItemStack("frostplate", 1)),
            xpPerCraft = 90,
            unlockToken = "recipe:frostforge",
            description = "A breastplate that never frosts over.",
        ),
        RecipeDefinition(
            id = "craft_frost_hood", name = "Line the Frost Hood", skillId = "armorcraft", skillLevelRequired = 4,
            timeSeconds = 14,
            inputs = listOf(ItemStack("froststeel", 1), ItemStack("frost_lumber", 1)),
            outputs = listOf(ItemStack("frost_hood", 1)),
            xpPerCraft = 70,
            unlockToken = "recipe:frostforge",
            description = "A hood lined with frostmoss.",
        ),
        RecipeDefinition(
            id = "craft_frostvein_ring", name = "Set the Frostvein Ring", skillId = "jewelry", skillLevelRequired = 4,
            timeSeconds = 16,
            inputs = listOf(ItemStack("frostvein", 1), ItemStack("froststeel", 1)),
            outputs = listOf(ItemStack("frostvein_ring", 1)),
            xpPerCraft = 80,
            unlockToken = "recipe:frostforge",
            description = "A ring set with a single living frostvein.",
        ),
        RecipeDefinition(
            id = "craft_icebound_amulet", name = "Cut the Icebound Amulet", skillId = "jewelry", skillLevelRequired = 4,
            timeSeconds = 16,
            inputs = listOf(ItemStack("frostvein", 1), ItemStack("glass_shard", 1)),
            outputs = listOf(ItemStack("icebound_amulet", 1)),
            xpPerCraft = 80,
            unlockToken = "recipe:frostforge",
            description = "Glass and frostvein that steady breath.",
        ),
        RecipeDefinition(
            id = "craft_pickaxe_frostforge", name = "Forge the Frostforge Pickaxe", skillId = "blacksmithing", skillLevelRequired = 4,
            timeSeconds = 16,
            inputs = listOf(ItemStack("froststeel", 1), ItemStack("frost_lumber", 2)),
            outputs = listOf(ItemStack("pickaxe_frostforge", 1)),
            xpPerCraft = 80,
            unlockToken = "recipe:frostforge",
            description = "A pickaxe that never warms to the rock.",
        ),
        RecipeDefinition(
            id = "eng_ward_frost", name = "Seal the Ward of Frost", skillId = "engineering", skillLevelRequired = 4,
            timeSeconds = 16,
            inputs = listOf(ItemStack("frostvein", 1), ItemStack("froststeel", 1)),
            outputs = listOf(ItemStack("ward_frost", 1)),
            xpPerCraft = 85,
            unlockToken = "recipe:frostforge",
            description = "Frostvein sealed in froststeel, stilling the shatter.",
        ),
    ).associateBy { it.id }

    fun get(id: RecipeId): RecipeDefinition = all[id]
        ?: error("Unknown recipe def '$id' (content gap)")

    fun availableRecipes(unlocks: Set<String>): List<RecipeDefinition> =
        all.values.filter { it.unlockToken.isEmpty() || unlocks.contains(it.unlockToken) }
            .sortedBy { it.skillLevelRequired }
}